 services:
  server:
    build:
      target: server
    container_name: rsc-server
    depends_on:
      mariadb:
        condition: service_healthy
    links:
      - mariadb
    volumes:
      - ./server/local.conf:/server/local.conf
      - ./server/connections.conf:/server/connections.conf
    ports:
      - ${OPENRSC_TCP_PORT:-43594}:43594
      - ${OPENRSC_WS_PORT:-43494}:43494
  client:
    build:
      target: client
    cap_add:
      - NET_ADMIN
    container_name: rsc-client
    ports:
      - ${CLIENT_PORT:-3333}:80
  mariadb:
    build:
      target: mariadb
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: rsc-db
    restart: always
    environment:
      - MARIADB_DATABASE=openrsc
      - MARIADB_USER=${DB_USER:-openrsc}
      - MARIADB_PASSWORD=${DB_PASSWORD:-openrsc}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD:-root}
      - MARIADB_ALLOW_EMPTY_PASSWORD=no
    ports:
      - "${DB_PORT:-3307}:3306"
    volumes:
      - ./.db:/var/lib/mysql